#remote_theme: jekyll/minima
remote_theme: jekyll/minima@d4d779a

title: Yotuna app

author:
  name: Yotuna team
  email: yotuna@mobulum.com

google_analytics: G-BJNTDEQJ7Z

minima:
  skin: classic
  nav_pages:
    - index.md
    - privacy.md
  social_links:
    - title: Discord server Mobulum/Yotuna app
      icon: discord
      url: "https://discord.gg/mrGKWMSTs2"

